version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    
    environment:
      MYSQL_ROOT_PASSWORD: Infinity@1
      MYSQL_DATABASE: rec_2024
      MYSQL_USER: vedant
      MYSQL_PASSWORD: Infinity@1
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    command: rails server -b 0.0.0.0
    depends_on:
      - db
    networks:
      - my_network
  nginx:
    image: nginx:latest
    depends_on:
      - web
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx_data:/etc/nginx
       
    
    networks:
      - my_network
  

networks:
  my_network:
    driver: bridge
  
volumes:
  nginx_data:
  db_data:
